### ISSUE TITLE
[Question] How to replicate RxCpp's defer action?

### ISSUE THREAD

**Issue by faizol** [CODIANZ/another-rxcpp#2]
Hi,

 I am trying to familiarize myself with another-rxcpp by trying to port examples from rxcpp to using this library. Among the rxcpp's examples, quite a few of them use "defer" action which is defined as "Returns an observable that calls the specified observable factory to create an observable for each new observer that subscribes." (link: http://reactivex.io/RxCpp/classrxcpp_1_1observable_3_01void_00_01void_01_4.html#ab8dd5d24ab381f227b138cfe22ffc16f).

What steps should I use to compose the same functionality using another-rxcpp as provided by RxCpp's defer action?

Thank you.

Cheers,

**Comment by terukazu-inoue** [comment]
Hi,
Thank you for posting.
I will make it from now on.
Please wait a moment!

**Comment by terukazu-inoue** [comment]
I tried implementing observable `defer`. Currently, we are pushing with `develop branch`. I think it works fine in the test code. I would be grateful if you could check it out.

https://github.com/CODIANZ/another-rxcpp/commit/09c7b5c8131194ab8ccb378bc73069729ebd2d66

**Comment by faizol** [comment]
> I tried implementing observable `defer`. Currently, we are pushing with `develop branch`. I think it works fine in the test code. I would be grateful if you could check it out.
> 
> [09c7b5c](https://github.com/CODIANZ/another-rxcpp/commit/09c7b5c8131194ab8ccb378bc73069729ebd2d66)

Thank you. I will test it with rxcpp's example and will get back to you on this. On a side note, is there any roadmap or future plan for this library? There is another new library being developed to "replace" rxcpp but using C++20; https://github.com/victimsnino/ReactivePlusPlus/. I am thinking of studying the source code for both libraries and if qualified, to contribute to either of the libraries since I might be heavily using it in the near future. There is a talk on youtube by Kirk Shoop detailing rxcpp's usage on his twitter analysis example (link: https://www.youtube.com/watch?v=1-8gxwGN3S8), and starting at 7.25 minute he discussed about tweet handling performances using callback, promise and subscription from his twitter analysis sample program. If most of the methods from https://reactivex.io/ are implemented, then perhaps I could start porting the RxCpp's examples to start using this library as a start? Or perhaps I could start by contributing some basic documentations first which will be essential for newbies like me.

Cheers,

**Comment by terukazu-inoue** [comment]
We are mainly developing payment systems. Payment systems must implement complex asynchronous processing such as Bluetooth devices, internet communication, user input, and each error. And there are strict regulations about speed. So we adopted "RxCpp" and used it for about 7 years.

Initially, "RxCpp" was used only for some logic parts, but the implementation scale has expanded, and now "RxCpp" is used throughout the project.

And then there was a very big problem.

That is, the memory and time consumption at compile time is enormous. (In the worst case, it consumes 10GB of memory and over an hour to compile a single file)

Therefore, we have developed "another-rxcpp" which is a replacement for "RxCpp" so that the code using the existing "RxCpp" can be used as it is. And now, the payment system we are developing has been completely replaced from "RxCpp" to "another-rxcpp" and has passed many tests and was released to the market.

In contrast, "ReactivePlusPlus" intends to replace "RxCpp" with an approach that takes advantage of the features of "C ++ 20". However, it cannot be evaluated because the most important operator "flat_map" of "Rx" does not exist at this time. Personally, I feel that "means" is "purpose".

Our goal is not to make "another-rxcpp". I have no intention of competing with "ReactivePlusPlus". In the future, if "RxCpp" can improve our problem, we will adopt "RxCpp", but at the moment it is unlikely that it will be improved.

We have released it as "another-rxcpp" to help people who are still experiencing the same problems as us. If anyone who needs "another-rxcpp" wants to add more features, we would be happy to implement it. (Of course, participation is also welcome!)
